image: golang:1.12.5

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - test

smoketest:
  stage: test
  script:
    - curl -fsSL https://get.docker.com | sh
    - ./kind-smoketest.sh
