name: Kind in CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - uses: actions/checkout@v1
    - name: Create K8S Cluster by kind
      id: kind
      uses: engineerd/setup-kind@v0.1.0
      with:
        config: hack/github/cluster.yaml
    - name: Install local-path provisioner
      id: local-path
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path)"
        kubectl wait --for=condition=Ready nodes --all --timeout=5m
        kubectl get nodes
        kubectl delete storageclass --all
        kubectl apply -f https://github.com/rancher/local-path-provisioner/raw/master/deploy/local-path-storage.yaml
        kubectl wait --for=condition=Ready pods -n local-path-storage --all --timeout=5m
    
    
